In [18]:
from qiskit.quantum_info import *
from qiskit import *

import numpy as np

from HamOp import *

from math import *

In [19]:
pauli1 = "XXI"
pauli2 = "IXX"

lista_pauli = [pauli1, pauli2];
print(lista_pauli)
print([lista_pauli,lista_pauli])

['XXI', 'IXX']
[['XXI', 'IXX'], ['XXI', 'IXX']]


In [20]:
print(lista_pauli[0])

XXI


In [21]:
lista_pauli.append(pauli1)

In [22]:
print(lista_pauli + lista_pauli)

['XXI', 'IXX', 'XXI', 'XXI', 'IXX', 'XXI']


In [23]:
p = SparsePauliOp(lista_pauli)

In [24]:
print(p)

SparsePauliOp(['XXI', 'IXX', 'XXI'],
              coeffs=[1.+0.j, 1.+0.j, 1.+0.j])


In [25]:
p.num_qubits

3

In [26]:
p.coeffs

array([1.+0.j, 1.+0.j, 1.+0.j])

In [27]:
pp = SparsePauliOp("I")

In [28]:
a = np.zeros(3) + 1/4
a

array([0.25, 0.25, 0.25])

In [29]:
a = a + 1/4

In [30]:
np.concatenate([a,a,a])

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [31]:
h = crea_hamiltonianaOp(4, True)

In [32]:
h.tot.argsort()

array([ 1,  5,  9,  2,  6, 10,  3,  0,  7,  4, 11,  8])

In [33]:
h.tot[h.tot.argsort()]

SparsePauliOp(['IIXX', 'IIYY', 'IIZZ', 'IXXI', 'IYYI', 'IZZI', 'XIIX', 'XXII', 'YIIY', 'YYII', 'ZIIZ', 'ZZII'],
              coeffs=[0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j])

In [47]:
a = h.tot.power(2).group_commuting()

In [49]:
len(a)

6

In [50]:
a @ h.tot

TypeError: unsupported operand type(s) for @: 'list' and 'SparsePauliOp'